In [333]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib.ticker import PercentFormatter

df_desordenado = pd.read_csv('../data/fantasy_data.csv')
df_desordenado = df_desordenado.drop(["PPGTarget_half-ppr","PointsTarget_half-ppr"], axis=1)

In [334]:
df_ordenado = df_desordenado.sort_values('Year')
df_ordenado = df_ordenado[~df_ordenado['Year'].between(1970, 1999)]
df_ordenado

,Player,Tm,Pos,Age,G,GS,Pass_Cmp,Pass_Att,Pass_Yds,Pass_TD,...,PPG_half-ppr,PPT_half-ppr,PointsOvrRank_half-ppr,PointsPosRank_half-ppr,PPGOvrRank_half-ppr,PPGPosRank_half-ppr,PPTOvrRank_half-ppr,PPTPosRank_half-ppr,Points_VORP_half-ppr,PPG_VORP_half-ppr
12838,Qadry Ismail,BAL,WR,30,15,13,0,0,0,0,...,8.000000,2.448980,105,42,122,42,55,41,-16.00,-1.443750
9035,Jeff Garcia,SFO,QB,30,16,16,355,561,4278,31,...,21.782500,0.550585,4,2,4,2,364,6,142.08,7.216250
25833,Derrius Thompson,WAS,WR,23,4,0,0,0,0,0,...,0.000000,0.000000,470,164,470,164,470,164,-136.00,-9.443750
23353,Mike Sellers,WAS,TE,25,15,6,0,0,0,0,...,1.600000,2.666667,287,44,327,47,38,10,-52.90,-3.406250
5027,KaRon Coleman,DEN,RB,22,9,0,0,0,0,0,...,2.588889,0.423636,290,90,273,81,399,133,-105.50,-6.861111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16849,Tay Martin,TEN,WR,27,1,0,0,0,0,0,...,11.400000,11.400000,396,155,92,29,2,2,-149.80,0.394118
16766,David Martin-Robinson,TEN,TE,25,5,2,0,0,0,0,...,0.220000,1.100000,515,110,509,104,298,96,-111.30,-7.797647
16736,Terrace Marshall Jr.,LVR,WR,24,7,1,0,0,0,0,...,0.800000,1.866667,447,175,439,175,171,125,-155.60,-10.205882
17679,Tanner McLachlan,CIN,TE,25,2,0,0,0,0,0,...,0.000000,0.000000,541,116,541,116,541,116,-112.40,-8.017647


In [335]:
df_ordenado["Year"]

12838    2000
9035     2000
25833    2000
23353    2000
5027     2000
         ... 
16849    2024
16766    2024
16736    2024
17679    2024
29368    2024
Name: Year, Length: 14893, dtype: int64

In [336]:
df_ordenado["games_played_pct"] = df_ordenado["games_played_pct"].round(5)
df_ordenado["games_played_pct"].value_counts()

games_played_pct
1.00000    4319
0.93750    1212
0.87500     904
0.81250     682
0.06250     673
0.75000     559
0.12500     549
0.18750     484
0.68750     466
0.62500     464
0.50000     452
0.31250     429
0.25000     428
0.43750     415
0.37500     409
0.56250     384
0.94118     268
0.88235     193
0.05882     175
0.11765     141
0.82353     136
0.76471     132
0.17647     129
0.70588     124
0.64706      99
0.52941      99
0.47059      98
0.29412      96
0.58824      93
0.35294      90
0.23529      90
0.41176      84
0.00000      13
1.06250       3
1.05882       1
Name: count, dtype: int64

In [337]:
df_ordenado["games_played_pct"] = df_ordenado["games_played_pct"].replace([1.06250,1.05882 ], 1)
df_ordenado["games_played_pct"].value_counts()

games_played_pct
1.00000    4323
0.93750    1212
0.87500     904
0.81250     682
0.06250     673
0.75000     559
0.12500     549
0.18750     484
0.68750     466
0.62500     464
0.50000     452
0.31250     429
0.25000     428
0.43750     415
0.37500     409
0.56250     384
0.94118     268
0.88235     193
0.05882     175
0.11765     141
0.82353     136
0.76471     132
0.17647     129
0.70588     124
0.64706      99
0.52941      99
0.47059      98
0.29412      96
0.58824      93
0.23529      90
0.35294      90
0.41176      84
0.00000      13
Name: count, dtype: int64

In [338]:
df_ordenado["games_started_pct"] = df_ordenado["games_started_pct"].round(5)
df_ordenado["games_started_pct"].value_counts()

games_started_pct
0.00000    4864
1.00000    2506
0.50000     449
0.25000     302
0.12500     298
           ... 
0.82353      17
0.64706      15
0.29412      14
0.88235      13
0.27778       1
Name: count, Length: 98, dtype: int64

In [339]:
df_t_mas_1 = df_ordenado[['Key', 'Year', 'PointsPosRank_half-ppr']].copy()
df_t_mas_1['Year'] = df_t_mas_1['Year'] - 1
df_t_mas_1 = df_t_mas_1.rename(columns={'PointsPosRank_half-ppr': 'Rank_t_plus_1'})

In [340]:
df_final = pd.merge(df_ordenado, df_t_mas_1, on=['Key', 'Year'], how='left')

In [341]:
year_maximo = df_final['Year'].max()
df_final = df_final[df_final['Year'] < year_maximo].copy()

In [342]:
df_final['y'] = df_final['Rank_t_plus_1'].fillna(999).apply(lambda x: 1 if x <= 12 else 0)

In [343]:
df_final['Year']

0        2000
1        2000
2        2000
3        2000
4        2000
         ... 
14259    2023
14260    2023
14261    2023
14262    2023
14263    2023
Name: Year, Length: 14264, dtype: int64

In [344]:
cols_to_drop = ['y', 'Rank_t_plus_1', 'Player', 'Key', 'Tm'] 
X = df_final.drop(cols_to_drop, axis=1)
y = df_final['y']

In [345]:
year_test = 2023 

data_train = df_final[df_final['Year'] < year_test].copy()
data_test  = df_final[df_final['Year'] == year_test].copy()

cols_a_quitar = ['y', 'Rank_t_plus_1', 'Player', 'Key', 'Tm'] 

X_train = data_train.drop(columns=cols_a_quitar, errors='ignore')
y_train = data_train['y']

X_test = data_test.drop(columns=cols_a_quitar, errors='ignore')
y_test = data_test['y']

In [346]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# ... (Tus pasos de carga y split anteriores están bien) ...

# 1. SELECCIÓN DE VARIABLES (CORREGIDO)
# Obtenemos las numéricas
numeric_features = X_train.select_dtypes(include=['float64', 'int64']).columns.values

# CORRECCIÓN 1: Eliminar 'AllPro', 'ProBowl' (y 'y' si estuviera) correctamente
columnas_a_excluir = ['y', 'AllPro', 'ProBowl']
numeric_features = numeric_features[~np.isin(numeric_features, columnas_a_excluir)]

# Obtenemos las categóricas
category_features = X_train.select_dtypes(include=['object', 'bool']).columns.values

# CORRECCIÓN 2: Agregar 'AllPro' y 'ProBowl' a la lista de categóricas
category_features = np.append(category_features, ['AllPro', 'ProBowl'])

print("Variables numéricas:", numeric_features)
print("Variables categóricas:", category_features)

Variables numéricas: ['Age' 'G' 'GS' 'Pass_Cmp' 'Pass_Att' 'Pass_Yds' 'Pass_TD' 'Pass_Int'
 'Rush_Att' 'Rush_Yds' 'Rush_Y/A' 'Rush_TD' 'Rec_Tgt' 'Rec_Rec' 'Rec_Yds'
 'Rec_Y/R' 'Rec_TD' 'Fmb' 'FmbLost' 'Scrim_TD' 'Year' 'Pass_Y/A'
 'Scrim_Yds' 'num_games' 'games_played_pct' 'games_started_pct' 'Exp'
 'Touches' 'Pass_Cmp%' 'Rec_Catch%' 'Pass_Cmp_per_game'
 'Pass_Att_per_game' 'Pass_Yds_per_game' 'Pass_TD_per_game'
 'Pass_Int_per_game' 'Rush_Att_per_game' 'Rush_Yds_per_game'
 'Rush_TD_per_game' 'Rec_Tgt_per_game' 'Rec_Rec_per_game'
 'Rec_Yds_per_game' 'Rec_TD_per_game' 'Fmb_per_game' 'FmbLost_per_game'
 'Scrim_TD_per_game' 'Scrim_Yds_per_game' 'Touches_per_game'
 'Points_half-ppr' 'PPG_half-ppr' 'PPT_half-ppr' 'PointsOvrRank_half-ppr'
 'PointsPosRank_half-ppr' 'PPGOvrRank_half-ppr' 'PPGPosRank_half-ppr'
 'PPTOvrRank_half-ppr' 'PPTPosRank_half-ppr' 'Points_VORP_half-ppr'
 'PPG_VORP_half-ppr']
Variables categóricas: ['Pos' 'AllPro' 'ProBowl']


In [347]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.combine import SMOTETomek

# Numéricas: Rellenar nulos con mediana y escalar
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])

# Categóricas: Rellenar nulos y convertir a OneHot
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))]) # Importante: ignore para categorías nuevas en test

# Combinar todo en el ColumnTransformer
# NOTA: Asegúrate de usar las listas 'numeric_features' y 'category_features' corregidas del paso anterior
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features), # Usar tu lista corregida
        ('cat', categorical_transformer, category_features)]) # Usar tu lista corregida

# Ajustamos el preprocesador solo con TRAIN
X_train_transformed = preprocessor.fit_transform(X_train)
# Transformamos el TEST (sin ajustar de nuevo)
X_test_transformed = preprocessor.transform(X_test)

In [348]:
print(f"Dimensiones originales Train: {X_train_transformed.shape}")
print(f"Balance de clases original: {y_train.value_counts().to_dict()}")

smt = SMOTETomek(random_state=42)

# Aquí ocurre la magia: Genera sintéticos y limpia ruido
X_train_resampled, y_train_resampled = smt.fit_resample(X_train_transformed, y_train)

print(f"Nuevas dimensiones Train: {X_train_resampled.shape}")
print(f"Nuevo balance de clases: {y_train_resampled.value_counts().to_dict()}")

Dimensiones originales Train: (13632, 66)
Balance de clases original: {0: 12601, 1: 1031}
Nuevas dimensiones Train: (25184, 66)
Nuevo balance de clases: {0: 12592, 1: 12592}


In [ ]:
from sklearn.model_selection import RandomizedSearchCV

random_grid = {
    'n_estimators': [100, 200, 300, 500],        # Número de árboles
    'max_depth': [None, 10, 20, 30, 50],         # Profundidad máxima del árbol
    'min_samples_split': [2, 5, 10],             # Mínimo de datos para dividir un nodo
    'min_samples_leaf': [1, 2, 4],               # Mínimo de datos en una hoja final
    'bootstrap': [True, False],                  # Si usa muestreo con reemplazo
    'class_weight': ['balanced', 'balanced_subsample', None] # Peso de clases
}

rf_base = RandomForestClassifier(random_state=42)

# cv=3 significa que usa Cross-Validation de 3 pliegues
rf_random = RandomizedSearchCV(
    estimator=rf_base,
    param_distributions=random_grid,
    n_iter=50,             # Número de combinaciones a probar (bájalo si tarda mucho)
    cv=3,                  # Validaciones cruzadas
    verbose=2,             # Para ver el progreso
    random_state=42,
    n_jobs=-1,             # Usa todos los núcleos de tu CPU
    scoring='recall'       # ¡IMPORTANTE! Optimizamos para RECALL (encontrar estrellas)
)

# 3. ENTRENAR LA BÚSQUEDA
print("Buscando los mejores hiperparámetros para Random Forest...")
# Entrenamos con tus datos balanceados
rf_random.fit(X_train_resampled, y_train_resa)

# 4. VER RESULTADOS
print("\nMejores parámetros encontrados:")
print(rf_random.best_params_)

# 5. PROBAR EL MEJOR MODELO
best_rf = rf_random.best_estimator_
y_pred_best = best_rf.predict(X_test_transformed) # Usamos el test original (transformado)

print("\n--- RESULTADOS DEL MEJOR RANDOM FOREST ---")
print(confusion_matrix(y_test, y_pred_best))
print(classification_report(y_test, y_pred_best))

Buscando los mejores hiperparámetros para Random Forest...
Fitting 3 folds for each of 50 candidates, totalling 150 fits

Mejores parámetros encontrados:
{'n_estimators': 500, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': None, 'class_weight': 'balanced', 'bootstrap': False}

--- RESULTADOS DEL MEJOR RANDOM FOREST ---
[[572  17]
 [ 30  13]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       589
           1       0.43      0.30      0.36        43

    accuracy                           0.93       632
   macro avg       0.69      0.64      0.66       632
weighted avg       0.92      0.93      0.92       632



In [350]:
lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_resampled, y_train_resampled)

y_pred_lr = lr.predict(X_test_transformed)

print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

[[504  85]
 [  7  36]]
              precision    recall  f1-score   support

           0       0.99      0.86      0.92       589
           1       0.30      0.84      0.44        43

    accuracy                           0.85       632
   macro avg       0.64      0.85      0.68       632
weighted avg       0.94      0.85      0.88       632



In [351]:
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=200, learning_rate=0.1, eval_metric='logloss', random_state=42)
xgb.fit(X_train_resampled, y_train_resampled)

y_pred_xgb = xgb.predict(X_test_transformed)

print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

[[575  14]
 [ 32  11]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96       589
           1       0.44      0.26      0.32        43

    accuracy                           0.93       632
   macro avg       0.69      0.62      0.64       632
weighted avg       0.91      0.93      0.92       632



In [352]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

knn.fit(X_train_resampled, y_train_resampled)

y_pred_knn = knn.predict(X_test_transformed)

print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

[[496  93]
 [ 17  26]]
              precision    recall  f1-score   support

           0       0.97      0.84      0.90       589
           1       0.22      0.60      0.32        43

    accuracy                           0.83       632
   macro avg       0.59      0.72      0.61       632
weighted avg       0.92      0.83      0.86       632

